version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/attendanceapp
    depends_on:
      - db
    networks:
      - attendance-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=attendance
      - MYSQL_USER=attendanceuser
      - MYSQL_PASSWORD=Saswe@123
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge

volumes:
  mysql_data: